# Generated by Django 4.1.13 on 2024-07-10 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_details', models.TextField(max_length=50)),
                ('task_type', models.CharField(choices=[('Pending', 'pending'), ('Done', 'done')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserTask.task')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
